version: '3.8'

services:
  app_laravel_cep:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_laravel_cep
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - "8080:8080" 
    networks:
      - laravel_network

  mysqladdress:
    image: mysql:8.0.27
    container_name: mysqladdress
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: address_docker
      MYSQL_USER: myuser
      MYSQL_PASSWORD: root
    volumes:
      - ${DB_DATA_FSSOURCE:-../sql-bind}:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  laravel_db_data:

